/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ClientTest{
  @Test
  public void instantiateswell_true(){
    Client newClient=new Client("leah");
    assertEquals(true, newClient instanceof Client);
  }
}
