/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 import org.sql2o.*;
 import org.junit.*;
 import static org.junit.Assert.*;

public class ClientTest{
  //set up test database
  @Before
  public void setUp(){
    DB.sql2o = new Sql2o("jdbc:postgresql://localhost:5432/hair_salon_test", "collins", "collins33");
  }

  //clearing database
  @After
  public void tearDown(){
    try(Connection con=DB.sql2o.open()){
      String sql="DELETE FROM clients *;";
      con.createQuery(sql).executeUpdate();
    }
  }

  //test for instance
  @Test
  public void instantiateswell_true(){
    Client newClient=new Client("leah");
    assertEquals(true, newClient instanceof Client);
  }
 //test if it instantiates with property of name
  @Test
  public void Client_instantiatesWithName_string(){
    Client newClient=new Client("leah");
    assertEquals("leah",newClient.getName());
  }
 //get time when client was registered
  
  @Test
  public void all_returnsAllInstancesOfClient_true(){
    Client newClient=new Client("leah");
    newClient.save();
    Client secondClient=new Client("anita");
    secondClient.save();
    assertEquals(true,Client.all().get(0).equals(newClient));
    assertEquals(true,Client.all().get(1).equals(secondClient));
  }

  @Test
  public void getId_clientInstantiateWithAnID_1(){

    Client newClient=new Client("leah");
    newClient.save();
    assertTrue(newClient.getId()>0);

  }
  @Test
  public void find_returnsClientWithSameId_secondTask(){
    Client newClient=new Client("leah");
    newClient.save();
    Client secondClient=new Client("anita");
    secondClient.save();
    assertEquals(Client.find(secondClient.getId()),secondClient);
  }

  //database tests
  @Test
  public void save_returnsTrueIfNamesAretheSame(){
    Client newClient=new Client("leah");
    newClient.save();
    assertTrue(Client.all().get(0).equals(newClient));
  }
  @Test
  public void save_assignsIdToObject(){
    Client newClient=new Client("leah");
    newClient.save();
    Client myClient =Client.all().get(0);
    assertEquals(newClient.getId(),myClient.getId());
  }
}
